Class review
DivaVocals/zen_Image-Handler pull request #228
Opened 2021-11-15 22:38 UTC by torvista

No changes to functionality. All based on IDE code inspections/complaints (based on php 7.1), intended to make real code changes later easier.
Code is in production on php8 with no issues with strict checks.

I intend to do the other files (that require far less work) prior to cleaning up the use of the width/heights integers/floats etc. that are scattered about liberally but need more examination.

2021-11-16 13:02 UTC, lat9 commented
Phew!  That's a slew of changes; I'll need some time to review.  Given that a lot of IH users are still (I know) on PHP 5.6, let's not go down the type-hinting path just yet to enable a wider audiences' use.

2021-11-16 13:39 UTC, torvista commented
> PHP 5.6
Good grief, and I thought I was being conservative with 7.1!

I find adding all these restrictions usually chases out something from under a stone, so they are worth it for development.

I'll reduce it to 5.6 level.

2021-11-19 13:37 UTC, lat9 requested changes
Just like my other comment, I think we need to explore **why** those values aren't integer values coming in and correct any issue at the source.

2021-11-19 13:38 UTC, lat9 requested changes
Same comment, find the source of the issue instead of 'correcting' at the usage.

2021-11-19 13:39 UTC, lat9 requested changes
Again, need to find the source of the !integer values, but I'll suggest removing the `@` since it's going to be useless with later versions of PHP anyhoo.

2021-11-19 13:43 UTC, lat9 commented on 1_Installation_Files (v1.5.5)/includes/classes/bmz_image_handler.class.php
> +                $image = false;
Please add a `break;` at the end of the default clause.

2021-11-19 15:22 UTC, lat9 commented
Let me know when you've finished; we'll get any other changes after retesting after the merge.

2021-11-19 15:24 UTC, torvista commented
Done.

2021-11-19 15:26 UTC, merged