Allow webp images to be processed
DivaVocals/zen_Image-Handler pull request #272
Opened 2023-02-06 18:03 UTC by brittainmark

Allow webp images

2023-02-06 19:49 UTC, lat9 commented
Solution for #262.  Thanks, @brittainmark; I'll review later today or in the morning.

2023-02-08 10:52 UTC, brittainmark commented
All fine corruption in my test environment.

2023-02-23 14:10 UTC, lat9 requested changes
Sorry it took so long to review!  Only changes are the minor ones to the readme.

2023-02-23 14:10 UTC, lat9 commented on docs/image_handler/readme.html
> +  <h3>Version 5.3.3 by lat9, Zen4All, brittainmark, torvista, proseLA and brittainmark</h3>
Next version is already 5.3.2; remove duplicate of name!

2023-02-23 21:55 UTC, brittainmark commented
No problem, I know you are busy. All done I hope.

2023-02-24 11:20 UTC, lat9 approved these changes

2023-02-24 11:20 UTC, merged